language: node_js
node_js:
- 8.1.4
sudo: false
dist: trusty

addons:
  apt:
    packages:
    - clang-3.9
    - clang-format-3.9
    - clang-tidy-3.9
    - build-essential

git:
  depth: 10

branches:
  only:
  - master

before_install:
- npm install -g npm@5.4.2

script:
- npm run ci:travis
- npm run lint
- npm run format && git diff

env:
  global:
  - CC=clang
  - CXX=clang++
  - npm_config_clang=1

notifications:
  email:
    on_success: never
    on_failure: change
