language: node_js
node_js:
- 7.4.0
sudo: false
dist: trusty

addons:
  apt:
    packages:
    - clang-3.3
    - build-essential

git:
  depth: 10

branches:
  only:
  - master

env:
  global:
  - CC=clang
  - CXX=clang++
  - npm_config_clang=1

script:
- find . -type f
- npm test

notifications:
  email:
    on_success: never
    on_failure: change
