language: node_js
node_js:
- 8.1.4
sudo: false
dist: trusty

addons:
  apt:
    sources:
    - llvm-toolchain-trusty-5.0
    packages:
    - clang-5.0
    - clang-format-5.0
    - clang-tidy-5.0
    - build-essential

git:
  depth: 10

branches:
  only:
  - master

before_install:
- mkdir -p ${HOME}/bin
- ln -s /usr/bin/clang-format-5.0 ${HOME}/bin/clang-format
- ln -s /usr/bin/clang-tidy-5.0 ${HOME}/bin/clang-tidy
- npm install -g npm@5.4.2

script:
- npm run ci:travis
- npm run lint
- npm run format && git diff --exit-code -- src/ test/

env:
  global:
  - CC=clang
  - CXX=clang++
  - npm_config_clang=1

notifications:
  email:
    on_success: never
    on_failure: change
