language: node_js
node_js:
- 7.9.0
sudo: false
dist: trusty
addons:
  apt:
    packages:
    - clang-3.9
    - build-essential
git:
  depth: 10
env:
  global:
  - CC=clang
  - CXX=clang++
  - npm_config_clang=1
  - secure: rBW+3CfuKKohLPy525/A1W6YezUQ7jxTGauYaDcugwa/jFJciO8xHJUJSBtT0HXL0sxYPGKCeN9uDgp1emMVOON0yYqQu3ia6aWJjrIWh1WQoMgaj67almNzVm8fDEbL17dw57fw3q1hGPmUxeFToIvVYhcTAVMVNfGBjQs5X9gpxOuGvUdd8uDhv/avVTKW5RLXAL9mznfCWeCnsEwMunr4le0FdyJvk2xxd05aj2Xw9VlYzV82e1dazSlbz3eb/QgghG10uuRF2LZyO4k7X82NBBpWml9RM3NwE7NBW1Awqakdd9bBIxmknAZwGQjEEqw2D8DDO1A/qnERhkE9KNIkpOv9wRyZUIFHE3UWZiOIhDPJifGKe5JV8EzGJ6lwePvA7jJxlQJOYXtOKzt91H9gZLIucYtOlMJHc/vo2ZzmhYRblDcQUf1+FSaFyiaC+GH1bJt/MYWYwmCkQSyp8rfKjPGdoTdZ1uyploFWIBuMFmN/X5cniMlhXddmWu8e2HUffpJch7CeFNujwqYrf8TJr7v+YxlWkqUfWIiXlRS1qHy3JsK1D+h11a+FvPLyfVdRLlKtmVmI4kqkxuU6UsVFaKYOBO2XYrXdcaAp3ZX4wdEoQdcwoE+n/72P2vQJVSStLspaK+yr52Vg5wje5EuUbIyLJDzBIqi9H5gjwmM=
  - secure: vwc00hh0xiH1vlkKIc9cFepIaj7L5yLXOzr8+g+tnygUxZMXyYCus67ZFC9GutOOm98M3RTPyUYNx/8pRRxzCshLqVs1PNDV7udgkINIHC9x7zI2N66xqE1lCCb8hRdiHbOZeu7d27PBTdIMXRuu5ff/Vc7kcNnzV/lYcFYZ2YgzZqhUOk8iI5czKuomH1Xdw4kUg+6v+HccDyUqocTu4co9d0vxz1r2cIY3r284ZcqwaG5/mThQQP9xTJ7hVPr66RGrKQP7+t134SLy4m9cAdw9cJnDLVzPeUNLaPIjQmrfAzGXYZmoftfNn2tcUs7IUX/gqYkVkxbZ5NrWCFERvNpyBuN8+0lKF7cT80y6TePeFlGgOmQKd7qF7FaCF+7JNM6HfmYyPu7BqzkDVkKQFknsZH0Ho9SfDtynzwtJoDwTwhuYaCIL7lICNC9Tvjt5YNuXEoO/gdhXCzOYcBdDBgOkETD4LmvMIH+PuolCPAMM1gYCxjcHt/NMRe2/vB5gVUQQo2ClCQnlaghjYujWT3g4TrcIlnLwiaSxQVOOXM/v7MFo7QG4QAMG0eL6Ca1QsfuBQzp7+ss/9pw6+x8EXHsqcenaaLg0xzvSJfeplu5qYhwcAdEd49Gjq/O+tszCmY6M6SB4wdyv1hk9WDAzT1tqyp2GKCiW5kGdvJ4wbRo=
branches:
  only:
  - master
  - "/^greenkeeper/.*$/"
before_install:
- npm install -g npm@latest greenkeeper-lockfile@1
install:
- npm install --build-from-source=@atom/watcher
before_script: greenkeeper-lockfile-update
script:
- npm run ci:travis
- npm run lint:js
after_script: greenkeeper-lockfile-upload
notifications:
  email:
    on_success: never
    on_failure: change
