version: 2

defaults: &defaults
  macos:
    xcode: 8.3.3
  environment:
  - NODE_VERSION: "7.9.0"

jobs:
  build:
    <<: *defaults
    steps:
    - checkout
    - run:
        name: install homebrew dependencies
        command: |
          brew update
          brew install nvm llvm
          export PATH=${PATH}:/usr/local/opt/llvm/bin
    - run:
        name: install node.js with nvm
        command: |
          export NVM_DIR=$(pwd)/.nvm
          mkdir -p ${NVM_DIR}
          echo "source /usr/local/opt/nvm/nvm.sh" >> ~/.bashrc
          source /usr/local/opt/nvm/nvm.sh
          nvm install ${NODE_VERSION}
          nvm alias default ${NODE_VERSION}
    - run: npm install
    - persist_to_workspace:
        root: .
        paths:
        - .nvm
        - node_modules
        - build

  test:
    <<: *defaults
    steps:
    - run:
        name: prepare environment
        command: |
          echo "source /usr/local/opt/nvm/nvm.sh" >> ~/.bashrc
          export PATH=${PATH}:/usr/local/opt/llvm/bin
          export NVM_DIR=$(pwd)/.nvm
    - checkout
    - attach_workspace:
        at: .
    - run: npm run ci:circle
    - store_test_results:
        path: test-results
    - store_artifacts:
        path: test-results

  lint:
    <<: *defaults
    steps:
    - run:
        name: prepare environment
        command: |
          echo "source /usr/local/opt/nvm/nvm.sh" >> ~/.bashrc
          export PATH=${PATH}:/usr/local/opt/llvm/bin
          export NVM_DIR=$(pwd)/.nvm
    - checkout
    - attach_workspace:
        at: .
    - run:
        name: lint js
        command: npm run lint:js
    - run:
        name: format c++
        command: npm run format && git diff --exit-code -- src/ test/
    - run:
        name: lint c++
        command: npm run lint:cpp

workflows:
  version: 2
  everything:
    jobs:
    - build
    - test:
        requires:
        - build
    - lint:
        requires:
        - build
