version: 2

defaults: &defaults
  macos:
    version: 7.3
  environment:
  - NVM_DIR: "${HOME}/.nvm"
  - NODE_VERSION: "7.9.0"
  - PATH: "${PATH}:/usr/local/opt/llvm/bin"

jobs:
  build:
    <<: *defaults
    steps:
    - checkout
    - run:
        name: install homebrew dependencies
        command: |
          brew update
          brew install nvm llvm
    - run:
        name: install node.js with nvm
        command: |
          mkdir -p ${NVM_DIR}
          echo "source /usr/local/opt/nvm/nvm.sh" >> ~/.bashrc
          nvm install ${NODE_VERSION}
          nvm alias default ${NODE_VERSION}
    - run: npm install
    - persist_to_workspace:
        root: .
        paths:
        - node_modules
        - build

  test:
    <<: *defaults
    steps:
    - checkout
    - attach_workspace:
        at: .
    - run: npm run ci:circle

  lint:
    <<: *defaults
    steps:
    - checkout
    - attach_workspace:
        at: .
    - run:
        name: lint js
        command: npm run lint:js
    - run:
        name: format c++
        command: npm run format && git diff --exit-code -- src/ test/
    - run:
        name: lint c++
        command: npm run lint:cpp

workflows:
  version: 2
  everything:
    jobs:
    - build
    - test:
        requires:
        - build
    - lint:
        required:
        - build
